### ISSUE TITLE
GCC's stdatomic.h/limits.h in lib/gcc/<triple>/<ver>/include break C11/C23 builds with clang on some targets (mips)

### ISSUE THREAD

**Issue by abcfy2** [cross-tools/clang-cross#5]
TL;DR:

The GCC headers (`stdatomic.h`, `limits.h`, ...) shipped in `lib/gcc/<TARGET>/<GCC version>/include/` shadow clang's own headers on some targets (e.g. `mips-unknown-linux-musl`), and they rely on GCC-specific builtin semantics that clang rejects. I had to delete these headers to make my builds pass.

Full issue:

I'm building static aria2 with the `mips-unknown-linux-musl` clang-cross toolchain (release 20260823, clang 22.1.8). OpenSSL 3.6.4 fails at:

```
crypto/core_namemap.c:103:31: error: address argument to atomic operation must be a pointer to a trivially-copyable type ('_Atomic(int) *' invalid)
  103 |     return namemap == NULL || tsan_load(&namemap->max_number) == 0;
include/internal/tsan_assist.h:61:24: note: expanded from macro 'tsan_load'
   61 | #define tsan_load(ptr) atomic_load_explicit((ptr), memory_order_relaxed)
/cross_root/bin/../lib/gcc/mips-unknown-linux-musl/16.2.0/include/stdatomic.h:146:5: note: expanded from macro 'atomic_load_explicit'
```

The same project builds fine with the musl-cross GCC 16.2.0 toolchain, and also builds fine with the armv7 clang-cross image. So I compared the two clang-cross images:

- `mips-unknown-linux-musl`: clang picks the GCC copy of `stdatomic.h`:

```
$ echo | mips-unknown-linux-musl-cc -E -v -xc - 2>&1 | sed -n '/search starts here/,/End of search list/p'
 /cross_root/bin/../lib/gcc/mips-unknown-linux-musl/16.2.0/../../../../mips-unknown-linux-musl/include
 /cross_root/bin/../lib/gcc/mips-unknown-linux-musl/16.2.0/include
 /cross_root/bin/../mips-unknown-linux-musl/sysroot/usr/include
 /cross_root/lib/clang/22/include
```

- `armv7-unknown-linux-musleabihf`: clang does NOT add `lib/gcc/<TARGET>/<ver>/include` to the search path, so clang's own `stdatomic.h` is used and everything compiles:

```
 /cross_root/bin/../lib/gcc/armv7-unknown-linux-musleabihf/16.2.0/../../../../armv7-unknown-linux-musleabihf/include
 /cross_root/bin/../armv7-unknown-linux-musleabihf/sysroot/usr/include
 /cross_root/lib/clang/22/include
```

Both images are clang 22.1.8 and both carry `stdatomic.h` in `lib/gcc/<TARGET>/16.2.0/include/`, so the difference is only whether clang picks it up.

Minimal repro (mips image):

```c
#include <stdatomic.h>
_Atomic int x = 0;
int main(void) { return (int)atomic_load_explicit(&x, memory_order_relaxed); }
```

```
$ mips-unknown-linux-musl-cc -c t.c
t.c:3:30: error: address argument to atomic operation must be a pointer to a trivially-copyable type ('_Atomic(int) *' invalid)
/cross_root/bin/../lib/gcc/mips-unknown-linux-musl/16.2.0/include/stdatomic.h:146:5: note: expanded from macro 'atomic_load_explicit'
```

GCC's `stdatomic.h` passes the original `_Atomic` pointer to the legacy `__atomic_load` builtin, and clang rejects `_Atomic`-qualified types there (https://github.com/llvm/llvm-project/issues/60572). With clang's own `stdatomic.h` the same code compiles.

Workaround I had to use:

- Deleting only `lib/gcc/<TARGET>/16.2.0/include/stdatomic.h` fixes OpenSSL, but then libiconv 1.19 fails on another header from the same directory:

```
rawmemchr.c:47:35: error: use of undeclared identifier '__SCHAR_WIDTH__'
   47 |   static_assert (UINTPTR_WIDTH == UCHAR_WIDTH * sizeof (uintptr_t));
/cross_root/bin/../lib/gcc/mips-unknown-linux-musl/16.2.0/include/limits.h:169:22: note: expanded from macro 'UCHAR_WIDTH'
  169 | # define UCHAR_WIDTH __SCHAR_WIDTH__
```

- Finally I deleted the whole `include/` and `include-fixed/` directories under `lib/gcc/<TARGET>/16.2.0/` (keeping `crt*.o` and `libgcc*.a` for linking). With that, my full aria2 static build (zlib-ng, xz, OpenSSL 3.6.4, libiconv 1.19, libxml2, sqlite, c-ares, libssh2, aria2) passes with clang for `mips-unknown-linux-musl`, and the binary runs fine under qemu-mips.

This looks like the same class as #1 (`stdckdint.h`), just in a different location: `lib/gcc/<TARGET>/<ver>/include/` instead of the sysroot.

Would you please fix this issue? Thanks.
